name: Build Python Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10" # Replace with your required Python version

    - name: Install Dependencies
      run: |
        python -m venv venv
        venv\Scripts\activate
        pip install --upgrade pip
        pip install pyinstaller

    - name: Build Executable
      run: |
        venv\Scripts\activate
        pyinstaller --onefile --noconsole src\app.py -n curlman
        dir dist # List the output directory

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: curlman
        path: dist\curlman.exe
